[package]
name = "ahrimq"
version = "0.0.1"
edition = "2021"
authors = ["ahriknow <ahriknow@ahriknow.com>"]
description = "A high-performance message queue service supporting pub/sub, ordered messages, delayed messages and dead letter queues."
license = "MIT"
repository = "https://github.com/ahriroot/ahrimq"
documentation = "https://github.com/ahriroot/ahrimq"
readme = "README.md"
keywords = [
    "message-queue",
    "mq",
    "pubsub",
    "distributed",
]
categories = ["asynchronous", "network-programming", "database-implementations"]

[[bin]]
name = "amqs"
path = "src/server/main.rs"

[[bin]]
name = "amqc"
path = "src/client/main.rs"

[lib]
name = "amq"
path = "src/lib/mod.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
