[package]
name = "ahrimq"
version = "0.0.1"
edition = "2021"
rust-version = "1.85"
authors = ["ahriknow <ahriknow@ahriknow.com>"]
description = "A high-performance message queue service supporting pub/sub, normal messages, ordered messages, delayed messages and dead letter queues."
license = "MIT"
repository = "https://github.com/ahriroot/ahrimq"
documentation = "https://github.com/ahriroot/ahrimq"
readme = "README.md"
keywords = [
    "ahrimq",
    "mq",
    "message-queue",
    "pubsub",
]
categories = ["asynchronous", "network-programming", "database-implementations"]

[[bin]]
name = "amqs"
path = "src/server/main.rs"

[[bin]]
name = "amqc"
path = "src/cli/main.rs"

[lib]
name = "amq"
path = "src/lib/mod.rs"

[dependencies]
bincode = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
